baseURL = 'https://su225.github.io/'
languageCode = 'en-us'
title = "Suchith's blog"
theme = "typo"
enableRobotsTXT = true

[taxonomies]
tag = 'tags'

[params]
theme = 'light'
homeIntroTitle = "Welcome to my blog"
homeIntroContent = """
I am a software engineer living in Amsterdam, the Netherlands. Currently,
I work as a backend developer. I am interested in distributed systems, databases,
systems programming and performance related stuffs.
"""

homeCollectionTitle = 'Posts'
homeCollection = 'posts'
paginationSize = 100
listDateFormat = '2 Jan 2006'
breadcrumbs = true

[params.author]
name = "Suchith J N"

[[params.social]]
name = "github"
url = "https://github.com/su225"

[[params.social]]
name = "linkedin"
url = "https://in.linkedin.com/in/suchithjn"

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

[markup]
    [markup.highlight]
    style = 'github'
    lineNos = false
    
    [markup.tableOfContents]
    ordered = false
    startLevel = 2
    endLevel = 10

    [markup.goldmark]
        [markup.goldmark.extensions]
        strikethrough = false
        [markup.goldmark.extensions.extras]
            [markup.goldmark.extensions.extras.delete]
                enable = true
            [markup.goldmark.extensions.extras.subscript]
                enable = true
            [markup.goldmark.extensions.extras.superscript]
                enable = true
