baseURL = 'https://su225.github.io/'
languageCode = 'en-us'
title = 'Tech notes'
theme = 'beautifulhugo'
enableRobotsTXT = true

[markup]
    [markup.highlight]
        lineNos = true
        style = 'dracula'
        anchorlinenos = true
    
    [markup.tableOfContents]
        ordered = true
        startLevel = 1
