baseURL = 'https://su225.github.io/'
languageCode = 'en-us'
title = 'Tech notes'
theme = 'beautifulhugo'
enableRobotsTXT = true

[Author]
    name = "Suchith J N"
    github = "su225"
    linkedin = "suchithjn"

[markup]
    [markup.highlight]
        lineNos = true
        style = 'dracula'
        anchorlinenos = true
    
    [markup.tableOfContents]
        ordered = false
        startLevel = 2

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about"
    weight = 3